### ISSUE TITLE
Use of JavaScript Date should probably be switched to Moment

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto-ui#29]
Both for stability and consistency with the rest of the Accord Project stack, it might be preferable to use `moment` for date creation rather than the custom use of the JavaScript `Date()` call.

This is notably affects code here: https://github.com/accordproject/concerto-ui/blob/f8b533d2e93d8526aa0bab708dcd0721f367c8ba/packages/concerto-ui-react/src/reactformvisitor.js#L243
or
here: https://github.com/accordproject/concerto-ui/blob/f8b533d2e93d8526aa0bab708dcd0721f367c8ba/packages/concerto-ui-react/src/reactformvisitor.js#L504-L520

Also creation of dates in local timezone cannot be easily tested.

**Comment by jeromesimeon** [comment]
A way around testing for the time being is included in PR #27

**Comment by martinhalford** [comment]
Yes - I came across the following Deprecation Warning while running the Cicero Server locally. 

`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: December 17, 2017 03:24:00, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/martin/Development/Accord/cicero/packages/cicero-server/node_modules/moment-mini/moment.min.js:1:3368)
    at Yt (/Users/martin/Development/Accord/cicero/packages/cicero-server/node_modules/moment-mini/moment.min.js:1:21318)
    at Ot (/Users/martin/Development/Accord/cicero/packages/cicero-server/node_modules/moment-mini/moment.min.js:1:22029)
    at Tt (/Users/martin/Development/Accord/cicero/packages/cicero-server/node_modules/moment-mini/moment.min.js:1:22111)
    at new c.parseZone (/Users/martin/Development/Accord/cicero/packages/cicero-server/node_modules/moment-mini/moment.min.js:1:50429)
    at JSONPopulator.convertToObject (/Users/martin/Development/Accord/cicero/packages/cicero-server/node_modules/@accordproject/concerto-core/lib/serializer/jsonpopulator.js:221:26)`

**Comment by raghav4** [comment]
@jeromesimeon can I work on this?

**Comment by raghav4** [comment]
@jeromesimeon I'm working on this.

**Comment by jeromesimeon** [comment]
@mttrbrts any thoughts on this issue?

**Comment by mttrbrts** [comment]
We should be careful to only add other dependencies where necessary as they bloat the bundle in downstream apps. 

Providing a robust implementation only for this one function should not necessarily require bringing in a whole date library.

This library doesn't have proper locale support now, so we should provide values in an RFC or ISO compliant format

**Comment by jeromesimeon** [comment]
> We should be careful to only add other dependencies where necessary as they bloat the bundle in downstream apps.
> 
> Providing a robust implementation only for this one function should not necessarily require bringing in a whole date library.
> 
> This library doesn't have proper locale support now, so we should provide values in an RFC or ISO compliant format

Moment is already a dependency for concerto.

**Comment by kanav-raina** [comment]
I would like to work on this, Kindly assign this to me.

**Comment by mttrbrts** [comment]
> Moment is already a dependency for concerto.

Concerto has `moment-mini` not `moment` as a dependency.

**Comment by mttrbrts** [comment]
I'd also like to reconsider the DatePicker component that we use here, we shouldn't have to use non-standard date formats

**Comment by kanav-raina** [comment]
I have changed moment to moment-mini @mttrbrts
